# LSTM

In [27]:
from numpy import array, newaxis, random
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

x = array(([[i*j for i in range(1, 10)] for j in range(2, 10)]))
y = array([i+2 for i in range(8)])
print(x.shape)
print(x)
print(y.shape)
print(y)

x = x[..., newaxis]
print(y.shape)

model = Sequential()
model.add(LSTM(20, activation="relu", input_shape=(9, 1)))
model.add(Dense(5))
model.add(Dense(1))
model.compile(optimizer="adam", loss="mse")

(8, 9)
[[ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
(8,)
[2 3 4 5 6 7 8 9]
(8,)


In [28]:
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor="loss", patience=3)
model.fit(x, y, epochs=1000, batch_size=1, verbose=2, callbacks=[early_stopping])

Epoch 1/1000
8/8 - 0s - loss: 1255.4285
Epoch 2/1000
8/8 - 0s - loss: 519.6676
Epoch 3/1000
8/8 - 0s - loss: 58.0305
Epoch 4/1000
8/8 - 0s - loss: 18.7594
Epoch 5/1000
8/8 - 0s - loss: 20.0714
Epoch 6/1000
8/8 - 0s - loss: 3.9827
Epoch 7/1000
8/8 - 0s - loss: 2.8630
Epoch 8/1000
8/8 - 0s - loss: 0.3911
Epoch 9/1000
8/8 - 0s - loss: 0.9784
Epoch 10/1000
8/8 - 0s - loss: 0.2676
Epoch 11/1000
8/8 - 0s - loss: 0.2183
Epoch 12/1000
8/8 - 0s - loss: 0.1523
Epoch 13/1000
8/8 - 0s - loss: 0.1224
Epoch 14/1000
8/8 - 0s - loss: 0.1262
Epoch 15/1000
8/8 - 0s - loss: 0.1011
Epoch 16/1000
8/8 - 0s - loss: 0.0985
Epoch 17/1000
8/8 - 0s - loss: 0.0918
Epoch 18/1000
8/8 - 0s - loss: 0.0914
Epoch 19/1000
8/8 - 0s - loss: 0.0897
Epoch 20/1000
8/8 - 0s - loss: 0.0848
Epoch 21/1000
8/8 - 0s - loss: 0.0849
Epoch 22/1000
8/8 - 0s - loss: 0.0790
Epoch 23/1000
8/8 - 0s - loss: 0.0784
Epoch 24/1000
8/8 - 0s - loss: 0.0754
Epoch 25/1000
8/8 - 0s - loss: 0.0767
Epoch 26/1000
8/8 - 0s - loss: 0.0702
Epoch 27/1000

In [29]:
x_input = array([(i+1)*15 for i in range(9)]).reshape(1, 9, 1)
print(f"x_input:\n {x_input}")
y_hat = model.predict(x_input)
print(f"y_hat:\n {y_hat[0][0]}")

x_input:
 [[[ 15]
  [ 30]
  [ 45]
  [ 60]
  [ 75]
  [ 90]
  [105]
  [120]
  [135]]]
y_hat:
 12.239938735961914


# RNN

In [39]:
from numpy import array, newaxis, random
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN
model = Sequential()
model.add(SimpleRNN(3, activation="relu", input_shape=(9, 1)))
model.add(Dense(5))
model.add(Dense(1))
model.compile(optimizer="adam", loss="mse")

In [40]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 1)                 12        
_________________________________________________________________
dense_16 (Dense)             (None, 5)                 10        
_________________________________________________________________
dense_17 (Dense)             (None, 1)                 6         
Total params: 28
Trainable params: 28
Non-trainable params: 0
_________________________________________________________________


In [31]:
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor="loss", patience=3)
model.fit(x, y, epochs=1000, batch_size=1, verbose=2, callbacks=[early_stopping])

Epoch 1/1000
8/8 - 0s - loss: 375.8824
Epoch 2/1000
8/8 - 0s - loss: 21.4433
Epoch 3/1000
8/8 - 0s - loss: 22.2808
Epoch 4/1000
8/8 - 0s - loss: 11.7915
Epoch 5/1000
8/8 - 0s - loss: 1.7029
Epoch 6/1000
8/8 - 0s - loss: 2.7743
Epoch 7/1000
8/8 - 0s - loss: 0.3151
Epoch 8/1000
8/8 - 0s - loss: 0.5525
Epoch 9/1000
8/8 - 0s - loss: 0.0379
Epoch 10/1000
8/8 - 0s - loss: 0.1036
Epoch 11/1000
8/8 - 0s - loss: 0.0109
Epoch 12/1000
8/8 - 0s - loss: 0.0169
Epoch 13/1000
8/8 - 0s - loss: 0.0063
Epoch 14/1000
8/8 - 0s - loss: 0.0059
Epoch 15/1000
8/8 - 0s - loss: 0.0044
Epoch 16/1000
8/8 - 0s - loss: 0.0046
Epoch 17/1000
8/8 - 0s - loss: 0.0043
Epoch 18/1000
8/8 - 0s - loss: 0.0055
Epoch 19/1000
8/8 - 0s - loss: 0.0043
Epoch 20/1000
8/8 - 0s - loss: 0.0047
Epoch 21/1000
8/8 - 0s - loss: 0.0042
Epoch 22/1000
8/8 - 0s - loss: 0.0040
Epoch 23/1000
8/8 - 0s - loss: 0.0042
Epoch 24/1000
8/8 - 0s - loss: 0.0044
Epoch 25/1000
8/8 - 0s - loss: 0.0041


In [32]:
x_input = array([(i+1)*15 for i in range(9)]).reshape(1, 9, 1)
print(f"x_input:\n {x_input}")
y_hat = model.predict(x_input)
print(f"y_hat:\n {y_hat[0][0]}")

x_input:
 [[[ 15]
  [ 30]
  [ 45]
  [ 60]
  [ 75]
  [ 90]
  [105]
  [120]
  [135]]]
y_hat:
 14.785452842712402
